
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "email": "logintest@test.com",
  "password": "test",
  "username": "LogintestUser",
  "first_name": "Login",
  "last_name": "TestUser"
}